version: '2'
services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./storage/mongodb:/data/db
    web_mongo:
        build: .
        container_name: web_mongo
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./storage/app:/var/www/storage/app
            - ./storage/logs:/var/www/storage/logs
